name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
#  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results
  security-events: write # allows OWASP DAST to show results in the Security tab
  contents: write # allows OWASP DAST to create issues/reports
  issues: write # Allows OWASP DAST to post the scan results as an issue

jobs:
  # SAST-SCA_Analysis:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   ######## SNYK FOR SCA SCAN
  #   - name: Snyk Open Source monitor
  #     uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
  #     env:
  #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #     with:
  #       args: --sarif-file-output=snyk.sarif
  #       projectBaseDir: .

  #   ######## SONAR FOR SAST SCAN
  #   - name: Analyze with SonarCloud
  #     uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
  #     env:
  #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     with:
  #       args: -Dsonar.projectKey=mayowafalana_guessing_game -Dsonar.organization=mayowafalana
  #       projectBaseDir: .

  ########## Build the Docker image and run OWASP ZAP scan on it in the runner before pushing to DockerHub
  OWASP-DAST-SCAN:
    runs-on: ubuntu-latest
    #needs: SAST-SCA_Analysis
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    #Checking if login is required here since I am not pushing the image to DockerHub yet, I am only building it and loading it into the runner's local storage to be scanned by OWASP ZAP. If login is required for the build process, then I will need to login here as well. If not, I can just login in the CD pipeline when I am ready to push to DockerHub.
    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKER_USER }}
    #     password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and NO push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false # Push is false here because I only want to build the image and run the OWASP DAST scan. I will push later in the CD pipeline if the SAST/SCA + OWASP DAST scans pass without any critical/high vulnerabilities.
        tags: guessing-game:latest
        load: true # This "loads" the image into your runner's local storage so ZAP can scan it

    ########## RUN OWASP ZAP SCAN ON THE BUILT IMAGE IN THE RUNNER
    - name: Run Container
      run: |
        docker run -d -p 8501:8501 --name streamlit-test \
        guessing-game:latest

    - name: Wait for App
      run: |
        sleep 30

    - name: OWASP ZAP Full Scan
      #uses: zaproxy/action-baseline@v0.10.0
      uses: zaproxy/action-full-scan@v0.13.0
      with:
        target: 'http://localhost:8501'
        artifact_name: 'zap-report'
        fail_action: false #True will fail the scan if any alert is found, False will not fail the scan regardless of the alerts found. Default is False.
        allow_issue_writing: false #Allows the action to create issues in the repository with the scan results. Default is false.
        #cmd_options: '-z "-config globalalertfilter=Critical"'

        # - name: Upload ZAP Report
        #   uses: actions/upload-artifact@v4
        #   if: always()
        #   with:
        #     name: zap-report
        #     path: report_html.html







        ###################### START CD PIPELINE AS A DIFFERENT JOB THAT DEPLOYS TO PRODUCTION IF THE SAST/SCA ANALYSIS -> OWASP DAST PASSES  
  CD-DEPLOY:
    runs-on: ubuntu-latest
    #needs: [ SAST-SCA_Analysis, OWASP-DAST-SCAN ]
    needs: [ OWASP-DAST-SCAN ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    ######## Create a timestamp environment variable to use as a unique tag for the Docker image
    - name: Timestamp
      run: |
        echo "DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Build and Push to DockerHub
      id: docker_build # Give this step an ID to reference its output
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true # I am push here because I am ready for delpoyment since the previous scans have passed.
        tags: |
          mayowafalana/guessing-game:${{ env.DATE }}
    #         mayowafalana/guessing-game:latest     
    #         mayowafalana/guessing-game:${{ github.sha }}

    ########## Use this to get the image hash and save it to env    
    - name: Get Digest
      run: echo "IMAGE_DIGEST=${{ steps.docker_build.outputs.digest }}" >> $GITHUB_ENV

    ########## Access Prod Server for Docker Compose
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/my-app
          docker login -u ${{ vars.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
          IMAGE_WITH_DIGEST="mayowafalana/guessing-game@${{ env.IMAGE_DIGEST }}"
          sed -i "s|image: mayowafalana/guessing-game.*|image: ${IMAGE_WITH_DIGEST}|g" docker-compose.yaml
          docker-compose pull
          docker-compose up -d
        # ########## SPLIT UP BUILD & PUSH using CLI commands instead of the docker/build-push-action
        #     - name: Build Image
        #       run: |
        #         docker build -t ${{ vars.DOCKER_USER }}/guessing-game:v1.1.5 .

        #     - name: Push Image
        #       run: |
        #         docker push ${{ vars.DOCKER_USER }}/guessing-game:v1.1.5

