# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "feature-ayobami" ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: gitleaks detection
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # trivy_scan:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Run fs scanner
  #       uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
  #       with:
  #         scan-type: 'fs'
  #         security-checks: secret
  #         format: 'template'
  #         template: '@/contrib/sarif.tpl'
  #         # output: 'trivy-fs-results.sarif'
  #         # severity: 'CRITICAL,HIGH'
  #         exit-code: 1


  #     - name: Build an image from Dockerfile
  #       run: |
  #         docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

  #     - name: Run Image scanner
  #       uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
  #       with:
  #         image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
  #         format: 'template'
  #         template: '@/contrib/sarif.tpl'
  #         output: 'trivy-results.sarif'
  #         severity: 'CRITICAL,HIGH'

  #     - name: Upload Trivy scan results to GitHub Security tab
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: 'trivy-results.sarif'
